"""
Report Generation Service — Phase 6
Generates professional PDF and DOCX drilling intelligence reports.
Templates: Well Intelligence, Offset Well Analysis, Field Intelligence, Management Summary.
"""
import io
import math
from datetime import datetime
from typing import Optional

# ─── PDF via ReportLab ────────────────────────────────────────
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, PageBreak,
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

# ─── DOCX via python-docx ─────────────────────────────────────
try:
    from docx import Document as DocxDocument
    from docx.shared import Pt, RGBColor, Inches, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


BRAND_BLUE = colors.HexColor("#1e40af") if REPORTLAB_AVAILABLE else None
BRAND_LIGHT = colors.HexColor("#eff6ff") if REPORTLAB_AVAILABLE else None
BRAND_GRAY = colors.HexColor("#374151") if REPORTLAB_AVAILABLE else None
BORDER_COLOR = colors.HexColor("#e5e7eb") if REPORTLAB_AVAILABLE else None


def _get_pdf_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle("NwisTitle",
        fontName="Helvetica-Bold", fontSize=22, textColor=BRAND_BLUE,
        spaceAfter=8, leading=26, alignment=TA_LEFT))

    styles.add(ParagraphStyle("NwisSubtitle",
        fontName="Helvetica", fontSize=12, textColor=BRAND_GRAY,
        spaceAfter=6, leading=16, alignment=TA_LEFT))

    styles.add(ParagraphStyle("NwisH1",
        fontName="Helvetica-Bold", fontSize=13, textColor=BRAND_BLUE,
        spaceBefore=14, spaceAfter=6))

    styles.add(ParagraphStyle("NwisH2",
        fontName="Helvetica-Bold", fontSize=11, textColor=BRAND_GRAY,
        spaceBefore=10, spaceAfter=4))

    styles.add(ParagraphStyle("NwisBody",
        fontName="Helvetica", fontSize=9, textColor=BRAND_GRAY,
        spaceAfter=3, leading=14, alignment=TA_JUSTIFY))

    styles.add(ParagraphStyle("NwisCaption",
        fontName="Helvetica-Oblique", fontSize=8,
        textColor=colors.HexColor("#6b7280"),
        spaceAfter=2, alignment=TA_LEFT))

    styles.add(ParagraphStyle("NwisLabel",
        fontName="Helvetica-Bold", fontSize=8,
        textColor=colors.HexColor("#6b7280"),
        spaceAfter=1))

    styles.add(ParagraphStyle("NwisValue",
        fontName="Helvetica", fontSize=9, textColor=BRAND_GRAY,
        spaceAfter=3))

    styles.add(ParagraphStyle("NwisAlert",
        fontName="Helvetica-Bold", fontSize=9,
        textColor=colors.HexColor("#dc2626"),
        spaceAfter=3, leading=13))

    styles.add(ParagraphStyle("NwisCell",
        fontName="Helvetica", fontSize=8, textColor=BRAND_GRAY,
        leading=10, alignment=TA_LEFT))

    return styles


def _table_style(header_color=None):
    hc = header_color or BRAND_BLUE
    return TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), hc),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 8),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, BRAND_LIGHT]),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
        ("GRID",          (0, 0), (-1, -1), 0.3, BORDER_COLOR),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING",   (0, 0), (-1, -1), 7),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 7),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ])


def _header_footer(canvas, doc, report_type, generated_by, generated_at):
    canvas.saveState()
    W, H = A4

    # Header bar
    canvas.setFillColor(BRAND_BLUE)
    canvas.rect(0, H - 1.2 * cm, W, 1.2 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(1.2 * cm, H - 0.75 * cm, "eRTMAC-NWIS  |  Nearby Wells Intelligence System  |  Oil India Limited")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(W - 1.2 * cm, H - 0.75 * cm, report_type)

    # Footer bar
    canvas.setFillColor(colors.HexColor("#f9fafb"))
    canvas.rect(0, 0, W, 0.9 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.HexColor("#9ca3af"))
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(1.2 * cm, 0.32 * cm, f"Generated by eRTMAC-NWIS AI Platform  |  {generated_by}  |  {generated_at}")
    canvas.drawRightString(W - 1.2 * cm, 0.32 * cm, f"Page {doc.page}")

    canvas.restoreState()


def generate_well_intelligence_pdf(well: dict, events: list, offset_wells: list, risks: list, generated_by: str = "System") -> bytes:
    """Generate a professional Well Intelligence Report PDF."""
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("ReportLab not installed")

    buf = io.BytesIO()
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    report_type = "Well Report"

    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=1.5*cm, rightMargin=1.5*cm,
        topMargin=2.2*cm, bottomMargin=1.5*cm,
    )
    doc.onFirstPage = lambda c, d: _header_footer(c, d, report_type, generated_by, generated_at)
    doc.onLaterPages = lambda c, d: _header_footer(c, d, report_type, generated_by, generated_at)

    styles = _get_pdf_styles()
    story = []

    # ── Cover ─────────────────────────────────────────────────
    story.append(Spacer(1, 1.5*cm))
    story.append(Paragraph("WELL REPORT", styles["NwisTitle"]))
    story.append(Paragraph(f"{well.get('well_name', '—')}  ·  {well.get('field_name', '—')}  ·  {well.get('basin_name', '—')}", styles["NwisSubtitle"]))
    story.append(Paragraph(f"Prepared: {generated_at}  ·  By: {generated_by}  ·  eRTMAC-NWIS v0.9", styles["NwisCaption"]))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_BLUE, spaceAfter=10))

    # ── Executive Summary ─────────────────────────────────────
    story.append(Paragraph("1. Executive Summary", styles["NwisH1"]))
    high_risk_count = sum(1 for r in risks if r.get("severity") in ("High", "Critical"))
    high_sev_events = sum(1 for e in events if e.get("severity") in ("High", "Critical"))
    summary_text = (
        f"This report provides a comprehensive intelligence analysis for <b>{well.get('well_name', '—')}</b>, "
        f"located in {well.get('field_name', '—')} field, {well.get('basin_name', '—')} basin. "
        f"The well has a planned total depth of {well.get('total_depth', '—')}m with {well.get('trajectory_type', '—')} trajectory. "
        f"<br/><br/>"
        f"Historical analysis identified <b>{len(events)} drilling events</b> associated with this operation, "
        f"of which <b>{high_sev_events}</b> were classified as High/Critical severity. "
        f"Risk prediction indicates <b>{high_risk_count} high or critical risks</b> ahead of current operations. "
        f"<b>{len(offset_wells)} offset wells</b> were analysed for similarity and knowledge transfer."
    )
    story.append(Paragraph(summary_text, styles["NwisBody"]))

    def wrap(t): return Paragraph(str(t), styles["NwisCell"])

    # ── Well Details ──────────────────────────────────────────
    story.append(Paragraph("2. Well Details", styles["NwisH1"]))
    well_data = [
        ["Parameter", "Value", "Parameter", "Value"],
        ["Well Name",   wrap(well.get("well_name", "—")),   "Well Status",   wrap(well.get("well_status", "—"))],
        ["Field",       wrap(well.get("field_name", "—")),   "Basin",         wrap(well.get("basin_name", "—"))],
        ["Latitude",    f"{well.get('latitude', '—')}°N", "Longitude",  f"{well.get('longitude', '—')}°E"],
        ["Total Depth", f"{well.get('total_depth', '—')}m", "Trajectory", wrap(well.get("trajectory_type", "—"))],
        ["Purpose",     wrap(well.get("well_purpose", "—")), "Hydrocarbon",   wrap(well.get("hydrocarbon_type", "—"))],
        ["Spud Date",   str(well.get("spud_date", "—"))[:10], "Completion", str(well.get("completion_date", "—"))[:10]],
    ]
    tbl = Table(well_data, colWidths=[3.5*cm, 5.5*cm, 3.5*cm, 5.5*cm])
    tbl.setStyle(_table_style())
    story.append(tbl)
    story.append(Spacer(1, 0.3*cm))

    # ── Drilling Events ───────────────────────────────────────
    story.append(Paragraph("3. Drilling Event History", styles["NwisH1"]))
    if events:
        ev_data = [["Event Type", "Severity", "Depth (m)", "NPT (h)", "Formation", "Cause"]]
        for e in events[:15]:
            ev_data.append([
                wrap(e.get("event_type", "—")),
                wrap(e.get("severity", "—")),
                str(e.get("start_depth", "—")),
                f"{e.get('npt_hours', 0):.1f}",
                wrap(e.get("formation", "—")),
                wrap(e.get("cause") or "—"),
            ])
        tbl2 = Table(ev_data, colWidths=[3.5*cm, 2.2*cm, 2.5*cm, 2.0*cm, 3.0*cm, 5.0*cm])
        tbl2.setStyle(_table_style())
        story.append(tbl2)
    else:
        story.append(Paragraph("No drilling events recorded for this well.", styles["NwisCaption"]))
    story.append(Spacer(1, 0.3*cm))

    # ── Offset Wells ──────────────────────────────────────────
    story.append(Paragraph("4. Offset Well Analysis", styles["NwisH1"]))
    if offset_wells:
        ow_data = [["Offset Well", "Field", "Distance", "Depth (m)", "Status", "Events"]]
        for ow in offset_wells[:10]:
            dist = ow.get("distance_km")
            dist_str = f"{dist:.1f}km" if isinstance(dist, (int, float)) else "—"
            ow_data.append([
                wrap(ow.get("well_name", "—")),
                wrap(ow.get("field_name", "—")),
                dist_str,
                str(ow.get("total_depth", "—")),
                wrap(ow.get("well_status", "—")),
                str(ow.get("event_count", "—")),
            ])
        tbl3 = Table(ow_data, colWidths=[4.0*cm, 3.5*cm, 2.5*cm, 2.5*cm, 2.5*cm, 2.5*cm])
        tbl3.setStyle(_table_style())
        story.append(tbl3)
    else:
        story.append(Paragraph("No offset wells available for comparison.", styles["NwisCaption"]))
    story.append(Spacer(1, 0.3*cm))

    # ── Risk Predictions ──────────────────────────────────────
    story.append(Paragraph("5. Risk Intelligence", styles["NwisH1"]))
    if risks:
        risk_data = [["Risk Type", "Window", "Depth (m)", "Confidence", "Severity", "Formation"]]
        for r in risks[:12]:
            risk_data.append([
                wrap(r.get("risk_type", "—")),
                wrap(r.get("window", "—")),
                f"{r.get('depth_start', '—')}–{r.get('depth_end', '—')}",
                f"{r.get('confidence', 0):.0f}%",
                wrap(r.get("severity", "—")),
                wrap(r.get("formation", "—")),
            ])
        tbl4 = Table(risk_data, colWidths=[3.5*cm, 3.5*cm, 3.0*cm, 2.5*cm, 2.5*cm, 3.0*cm])
        tbl4.setStyle(_table_style())
        story.append(tbl4)
    else:
        story.append(Paragraph("No significant risks predicted.", styles["NwisCaption"]))
    story.append(Spacer(1, 0.3*cm))

    # ── Recommendations ───────────────────────────────────────
    story.append(Paragraph("6. AI Recommendations", styles["NwisH1"]))
    recs = [
        "Monitor ECD relative to fracture gradient — maintain minimum 0.05sg safety margin at all times.",
        "Conduct flow checks at every formation boundary to detect early kick indicators.",
        "Maintain LCM inventory (fine, medium, coarse grades) prior to entering Barail Formation intervals.",
        "Review offset well event logs from adjacent wells before drilling through predicted high-risk intervals.",
        "Ensure BOP pressure test certification is current and kill procedures are rehearsed with crew.",
    ]
    for i, rec in enumerate(recs, 1):
        story.append(Paragraph(f"<b>R{i}:</b> {rec}", styles["NwisBody"]))

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR))
    story.append(Paragraph(
        f"This report was automatically generated by eRTMAC-NWIS AI Platform on {generated_at}. "
        "All risk assessments are based on historical operational data and predictive models. "
        "This report is for advisory purposes only and does not substitute engineering judgment.",
        styles["NwisCaption"],
    ))

    doc.build(story)
    return buf.getvalue()


def generate_well_intelligence_docx(well: dict, events: list, offset_wells: list, risks: list, generated_by: str = "System") -> bytes:
    """Generate a professional Well Intelligence Report DOCX."""
    if not DOCX_AVAILABLE:
        raise RuntimeError("python-docx not installed")

    doc = DocxDocument()
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Page margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = title.add_run("WELL REPORT")
    run.bold = True
    run.font.size = Pt(20)
    run.font.color.rgb = RGBColor(0x1e, 0x40, 0xaf)

    sub = doc.add_paragraph(f"{well.get('well_name', '—')}  ·  {well.get('field_name', '—')}  ·  {well.get('basin_name', '—')}")
    sub.runs[0].font.size = Pt(11)
    sub.runs[0].font.color.rgb = RGBColor(0x37, 0x41, 0x51)

    doc.add_paragraph(f"Prepared: {generated_at}  ·  By: {generated_by}  ·  eRTMAC-NWIS v0.9").runs[0].italic = True

    doc.add_heading("1. Executive Summary", level=1)
    high_sev = sum(1 for e in events if e.get("severity") in ("High", "Critical"))
    doc.add_paragraph(
        f"This report covers {well.get('well_name', '—')} in {well.get('field_name', '—')} field. "
        f"Total depth: {well.get('total_depth', '—')}m. Trajectory: {well.get('trajectory_type', '—')}. "
        f"Historical events: {len(events)} ({high_sev} high/critical). Offset wells analysed: {len(offset_wells)}."
    )

    doc.add_heading("2. Well Details", level=1)
    tbl = doc.add_table(rows=1, cols=4)
    tbl.style = "Table Grid"
    hdr = tbl.rows[0].cells
    for i, h in enumerate(["Parameter", "Value", "Parameter", "Value"]):
        hdr[i].text = h
        hdr[i].paragraphs[0].runs[0].bold = True

    rows = [
        ("Well Name", well.get("well_name", "—"), "Status", well.get("well_status", "—")),
        ("Field", well.get("field_name", "—"), "Basin", well.get("basin_name", "—")),
        ("Total Depth", f"{well.get('total_depth', '—')}m", "Trajectory", well.get("trajectory_type", "—")),
        ("Purpose", well.get("well_purpose", "—"), "Hydrocarbon", well.get("hydrocarbon_type", "—")),
    ]
    for r in rows:
        row = tbl.add_row().cells
        for i, v in enumerate(r):
            row[i].text = str(v)

    doc.add_heading("3. Drilling Events", level=1)
    if events:
        etbl = doc.add_table(rows=1, cols=5)
        etbl.style = "Table Grid"
        for i, h in enumerate(["Event Type", "Severity", "Depth (m)", "NPT (h)", "Formation"]):
            etbl.rows[0].cells[i].text = h
            etbl.rows[0].cells[i].paragraphs[0].runs[0].bold = True
        for e in events[:10]:
            row = etbl.add_row().cells
            row[0].text = e.get("event_type", "—")
            row[1].text = e.get("severity", "—")
            row[2].text = str(e.get("start_depth", "—"))
            row[3].text = f"{e.get('npt_hours', 0):.1f}"
            row[4].text = e.get("formation", "—") or "—"

    doc.add_heading("4. Risk Intelligence", level=1)
    if risks:
        rtbl = doc.add_table(rows=1, cols=4)
        rtbl.style = "Table Grid"
        for i, h in enumerate(["Risk Type", "Depth", "Confidence", "Severity"]):
            rtbl.rows[0].cells[i].text = h
            rtbl.rows[0].cells[i].paragraphs[0].runs[0].bold = True
        for r in risks[:8]:
            row = rtbl.add_row().cells
            row[0].text = r.get("risk_type", "—")
            row[1].text = f"{r.get('depth_start', '—')}–{r.get('depth_end', '—')}m"
            row[2].text = f"{r.get('confidence', 0):.0f}%"
            row[3].text = r.get("severity", "—")

    doc.add_heading("5. Recommendations", level=1)
    for i, rec in enumerate([
        "Monitor ECD — maintain 0.05sg safety margin below fracture gradient.",
        "Conduct flow checks at every formation boundary.",
        "Maintain LCM inventory prior to entering high-risk intervals.",
        "Review offset well event logs before drilling critical sections.",
    ], 1):
        doc.add_paragraph(f"R{i}: {rec}", style="List Number")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def generate_field_report_pdf(field: dict, wells: list, events: list, generated_by: str = "System") -> bytes:
    """Generate a Field Intelligence Report PDF."""
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("ReportLab not installed")

    buf = io.BytesIO()
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    report_type = "Field Report"

    doc = SimpleDocTemplate(buf, pagesize=A4,
        leftMargin=1.5*cm, rightMargin=1.5*cm,
        topMargin=2.2*cm, bottomMargin=1.5*cm)
    doc.onFirstPage = lambda c, d: _header_footer(c, d, report_type, generated_by, generated_at)
    doc.onLaterPages = lambda c, d: _header_footer(c, d, report_type, generated_by, generated_at)

    styles = _get_pdf_styles()
    story = []

    story.append(Spacer(1, 1.5*cm))
    story.append(Paragraph("FIELD REPORT", styles["NwisTitle"]))
    story.append(Paragraph(f"{field.get('name', '—')}  ·  {field.get('basin_name', '—')} Basin", styles["NwisSubtitle"]))
    story.append(Paragraph(f"Prepared: {generated_at}  ·  By: {generated_by}", styles["NwisCaption"]))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_BLUE, spaceAfter=10))

    story.append(Paragraph("1. Field Overview", styles["NwisH1"]))
    active = sum(1 for w in wells if w.get("well_status") in ("Drilling", "Producing"))
    total_npt = sum(e.get("npt_hours", 0) or 0 for e in events)

    fd = [
        ["Parameter", "Value"],
        ["Field Name", field.get("name", "—")],
        ["Basin", field.get("basin_name", "—")],
        ["Total Wells", str(len(wells))],
        ["Active Wells", str(active)],
        ["Total Events", str(len(events))],
        ["Total NPT", f"{total_npt:.1f} hours"],
    ]
    ftbl = Table(fd, colWidths=[6*cm, 12*cm])
    ftbl.setStyle(_table_style())
    story.append(ftbl)
    story.append(Spacer(1, 0.3*cm))

    story.append(Paragraph("2. Well Inventory", styles["NwisH1"]))
    if wells:
        wd = [["Well Name", "Status", "Depth (m)", "Trajectory", "Purpose"]]
        for w in wells[:20]:
            wd.append([
                w.get("well_name", "—"),
                w.get("well_status", "—"),
                str(w.get("total_depth", "—")),
                w.get("trajectory_type", "—"),
                w.get("well_purpose", "—"),
            ])
        wtbl = Table(wd, colWidths=[5*cm, 3*cm, 3*cm, 3*cm, 4*cm])
        wtbl.setStyle(_table_style())
        story.append(wtbl)

    story.append(Paragraph("3. Incident Summary", styles["NwisH1"]))
    if events:
        # Group by type
        by_type: dict = {}
        for e in events:
            t = e.get("event_type", "Unknown")
            if t not in by_type:
                by_type[t] = {"count": 0, "npt": 0.0}
            by_type[t]["count"] += 1
            by_type[t]["npt"] += e.get("npt_hours", 0) or 0

        ed = [["Event Type", "Count", "Total NPT (h)", "Avg NPT (h)"]]
        for evt_type, stats in sorted(by_type.items(), key=lambda x: x[1]["count"], reverse=True):
            ed.append([evt_type, str(stats["count"]),
                       f"{stats['npt']:.1f}", f"{stats['npt']/max(1,stats['count']):.1f}"])
        etbl = Table(ed, colWidths=[6*cm, 3*cm, 4*cm, 4*cm])
        etbl.setStyle(_table_style())
        story.append(etbl)

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR))
    story.append(Paragraph(
        f"Generated by eRTMAC-NWIS AI Platform on {generated_at}. For advisory purposes only.",
        styles["NwisCaption"]))

    doc.build(story)
    return buf.getvalue()


def generate_management_summary_pdf(overview: dict, generated_by: str = "System") -> bytes:
    """Generate a Management Summary Report PDF."""
    if not REPORTLAB_AVAILABLE:
        raise RuntimeError("ReportLab not installed")

    buf = io.BytesIO()
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    doc = SimpleDocTemplate(buf, pagesize=A4,
        leftMargin=1.5*cm, rightMargin=1.5*cm,
        topMargin=2.2*cm, bottomMargin=1.5*cm)
    doc.onFirstPage = lambda c, d: _header_footer(c, d, "Management Summary", generated_by, generated_at)
    doc.onLaterPages = lambda c, d: _header_footer(c, d, "Management Summary", generated_by, generated_at)

    styles = _get_pdf_styles()
    story = []

    story.append(Spacer(1, 1.5*cm))
    story.append(Paragraph("MANAGEMENT SUMMARY REPORT", styles["NwisTitle"]))
    story.append(Paragraph("eRTMAC-NWIS  ·  Operational Intelligence Dashboard", styles["NwisSubtitle"]))
    story.append(Paragraph(f"Prepared: {generated_at}  ·  By: {generated_by}", styles["NwisCaption"]))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_BLUE, spaceAfter=12))

    story.append(Paragraph("1. Operations Overview", styles["NwisH1"]))
    kpis = [
        ["KPI", "Value"],
        ["Total Wells in System", str(overview.get("total_wells", "—"))],
        ["Active Drilling Operations", str(overview.get("active_wells", "—"))],
        ["Total Fields", str(overview.get("total_fields", "—"))],
        ["Total Basins", str(overview.get("total_basins", "—"))],
        ["Total Documents Processed", str(overview.get("total_docs", "—"))],
        ["AI Chat Sessions", str(overview.get("total_sessions", "—"))],
        ["Total Drilling Events", str(overview.get("total_events", "—"))],
        ["Avg NPT per Event (h)", f"{overview.get('avg_npt', 0):.1f}"],
    ]
    ktbl = Table(kpis, colWidths=[10*cm, 8*cm])
    ktbl.setStyle(_table_style())
    story.append(ktbl)
    story.append(Spacer(1, 0.3*cm))

    story.append(Paragraph("2. Risk Status", styles["NwisH1"]))
    story.append(Paragraph(
        "The NWIS risk prediction engine continuously monitors offset well similarity and formation knowledge "
        "to provide proactive drilling hazard identification. The following risk categories are currently being tracked:",
        styles["NwisBody"]))
    for risk in ["Lost Circulation", "Stuck Pipe", "Kick / Well Control", "Torque Spike", "Formation Instability"]:
        story.append(Paragraph(f"• {risk}", styles["NwisBody"]))

    story.append(Paragraph("3. Platform Capabilities", styles["NwisH1"]))
    caps = [
        ["Module", "Status"],
        ["Well Explorer",           "✓ Operational"],
        ["Map Intelligence",        "✓ Operational"],
        ["Document Intelligence",   "✓ Operational"],
        ["AI Drilling Assistant",   "✓ Operational"],
        ["Live Rig Monitoring",     "✓ Operational"],
        ["Report Generator",        "✓ Operational"],
        ["Analytics",               "✓ Operational"],
    ]
    ctbl = Table(caps, colWidths=[10*cm, 8*cm])
    ctbl.setStyle(_table_style())
    story.append(ctbl)

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_COLOR))
    story.append(Paragraph(
        f"Generated by eRTMAC-NWIS AI Platform on {generated_at}. For advisory purposes only.",
        styles["NwisCaption"]))

    doc.build(story)
    return buf.getvalue()
